apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cc-gramine-demo

resources:
- issuer.yaml

generatorOptions:
  disableNameSuffixHash: true

# Generate tls.crt and tls.key:
# openssl genrsa -out tls.key 2048
# openssl req -x509 -new -nodes -key tls.key -subj "/CN=ccg-ca" -days 10000 -out tls.crt
secretGenerator:
- files:
  - tls.crt
  - tls.key
  name: ccg-ca-key-pair
  type: kubernetes.io/tls
