apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ra-tls-secret-prov
  name: secret-provider-server
  namespace: cc-gramine-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ra-tls-secret-prov
  template:
    metadata:
      labels:
        app: ra-tls-secret-prov
    spec:
      containers:
        - image: docker.io/library/gramine:devel
          name: ra-tls-secret-prov
          workingDir: "/ra-tls-secret-prov"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          command:
            - "./secret_prov_server_dcap"
          volumeMounts:
            - name: secret-key
              mountPath: "/ra-tls-secret-prov/files"
              readOnly: true
            - name: ra-tls-secret-prov-cert
              mountPath: "/ra-tls-secret-prov/certs"
              readOnly: true
            - name: qplconf
              mountPath: /etc/sgx_default_qcnl.conf
              subPath: sgx_default_qcnl.conf
      volumes:
        - name: secret-key
          configMap:
            name: ra-tls-secret-key
        - name: ra-tls-secret-prov-cert
          secret:
            secretName: ra-tls-secret-prov-cert
        - name: qplconf
          configMap:
            name: sgx-attestation-conf
            items:
            - key: sgx_default_qcnl.conf
              path: sgx_default_qcnl.conf
